import React from 'react';
import { Button, CssBaseline } from '@mui/material';
import { createTheme, ThemeProvider } from '@mui/material/styles';
import PropTypes from 'prop-types';

import Navbar from '../../components/Navbar';
import theme from '../../theme/palette';
import WelcomeImg from '../../assets/Welcome.png';
import Tutorial from './Tutorial';

const containerStyle = {
  width: '95%',
  maxWidth: '700px',
  marginTop: '10px',
  paddingLeft: '30px',
  paddingRight: '30px',
};

const imageStyle = {
  display: 'inline',
  width: '400px',
};

const buttonTheme = createTheme({
  palette: {
    primary: {
      main: theme.light,
    },
  },
});

const About = (props) => {
  return (
    <>
      <CssBaseline />
      <Navbar
        onLoginClick={props.onLoginClick}
        userLoggedIn={props.userLoggedIn}
        onAboutClick={props.onAboutClick}
        onLogoClick={props.onLogoClick}
      />
      <div style={{ display: 'flex', justifyContent: 'center' }}>
        <div className="welcome basic-container" style={containerStyle}>
          <div
            style={{
              display: 'flex',
              justifyContent: 'center',
              alignItems: 'center',
            }}
          >
            <img src={WelcomeImg} style={imageStyle} />
          </div>

          <p>
            Write with your favorite authors from beyond the grave! Be it 
            a sonnet with Shakespeare, a novel with Jane Austen, or an angry
            internet comment with Homer - the only limit is you (and the
            ghost's) imagination.
          </p>
          <Tutorial/>
          <p>
            <span style={{ color: theme.complement }}>
              <b>Warning:</b> The texts have not been filtered in any way.
              Unsavory (and possibly offensive) language in the original
              literature may be generated by this application.
            </span>
          </p>
          <div
            style={{
              display: 'flex',
              justifyContent: 'center',
              marginTop: '20px',
            }}
          >
            <div>
              <ThemeProvider theme={buttonTheme}>
                <Button onClick={props.onCloseClick} variant="outlined">
                  Let's go!
                </Button>
              </ThemeProvider>
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

About.propTypes = {
  onLoginClick: PropTypes.func.isRequired,
  userLoggedIn: PropTypes.bool.isRequired,
  onAboutClick: PropTypes.func.isRequired,
  onCloseClick: PropTypes.func.isRequired,
};

export default About;
